/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as DatosPersonalesRouteImport } from './routes/datos-personales'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as KitRouteImport } from './routes/kit'
import { Route as MiDocumentoRouteImport } from './routes/mi-documento'
import { Route as PlanProfesionalRouteImport } from './routes/plan-profesional'
import { Route as PlanesRouteImport } from './routes/planes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const DatosPersonalesRoute = DatosPersonalesRouteImport.update({
  id: '/datos-personales',
  path: '/datos-personales',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const MiDocumentoRoute = MiDocumentoRouteImport.update({
  id: '/mi-documento',
  path: '/mi-documento',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanProfesionalRoute = PlanProfesionalRouteImport.update({
  id: '/plan-profesional',
  path: '/plan-profesional',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ayuda': typeof AyudaRoute
  '/datos-personales': typeof DatosPersonalesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/kit': typeof KitRoute
  '/mi-documento': typeof MiDocumentoRoute
  '/plan-profesional': typeof PlanProfesionalRoute
  '/planes': typeof PlanesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ayuda': typeof AyudaRoute
  '/datos-personales': typeof DatosPersonalesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/kit': typeof KitRoute
  '/mi-documento': typeof MiDocumentoRoute
  '/plan-profesional': typeof PlanProfesionalRoute
  '/planes': typeof PlanesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ayuda': typeof AyudaRoute
  '/datos-personales': typeof DatosPersonalesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/kit': typeof KitRoute
  '/mi-documento': typeof MiDocumentoRoute
  '/plan-profesional': typeof PlanProfesionalRoute
  '/planes': typeof PlanesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ayuda'
    | '/datos-personales'
    | '/diagnostico'
    | '/kit'
    | '/mi-documento'
    | '/plan-profesional'
    | '/planes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ayuda'
    | '/datos-personales'
    | '/diagnostico'
    | '/kit'
    | '/mi-documento'
    | '/plan-profesional'
    | '/planes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ayuda'
    | '/datos-personales'
    | '/diagnostico'
    | '/kit'
    | '/mi-documento'
    | '/plan-profesional'
    | '/planes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AyudaRoute: typeof AyudaRoute
  DatosPersonalesRoute: typeof DatosPersonalesRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  KitRoute: typeof KitRoute
  MiDocumentoRoute: typeof MiDocumentoRoute
  PlanProfesionalRoute: typeof PlanProfesionalRoute
  PlanesRoute: typeof PlanesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datos-personales': {
      id: '/datos-personales'
      path: '/datos-personales'
      fullPath: '/datos-personales'
      preLoaderRoute: typeof DatosPersonalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit': {
      id: '/kit'
      path: '/kit'
      fullPath: '/kit'
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-documento': {
      id: '/mi-documento'
      path: '/mi-documento'
      fullPath: '/mi-documento'
      preLoaderRoute: typeof MiDocumentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-profesional': {
      id: '/plan-profesional'
      path: '/plan-profesional'
      fullPath: '/plan-profesional'
      preLoaderRoute: typeof PlanProfesionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AyudaRoute: AyudaRoute,
  DatosPersonalesRoute: DatosPersonalesRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  KitRoute: KitRoute,
  MiDocumentoRoute: MiDocumentoRoute,
  PlanProfesionalRoute: PlanProfesionalRoute,
  PlanesRoute: PlanesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
